### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by regisx001** [GlebBatykov/minerva#3]
Hello !!!!
I just started to be familiar with this framework, it's super useful and a great option,
I read the docs about it and i didnt find how to deal with files upload  and store them ,
Can You add how to deal with them in the documentation  ?
and thank you for this awesome project !!!!!!!

**Comment by GlebBatykov** [comment]
Hi!

I'm glad you liked the framework.

You can upload files to the server by transferring files via form-data. You pass the request body as form-data, you pass the file in one of the fields. Then you use the asForm method() at the request body and you get access to the file. And then, using the standard library dart:io, you already write the file wherever you want.

You can send files from the server by returning the FileResult result.

In general, there is a primitive example of working with files in this [example](https://github.com/GlebBatykov/minerva_examples/tree/main/examples/file_server).

I will improve the documentation of the framework and add information about it there.

**Comment by regisx001** [comment]
Ohhhh yeah that seem super easy to work with , I will try it !
thanks for help
