### ISSUE TITLE
Strange bug maybe related to MacOs Update

### ISSUE THREAD

**Issue by AreboursTLS** [GlebBatykov/minerva#5]
I'm using your great package for a while now. 

Since my last macOs Update (13.0 Ventura), i can't run any server.

`Entry point not found by path: /Users/.../.../MedApp/private_services/private_serv//build/debug/bin/main.dill.`

There is this // between the project root path and build that seems strange.

Even when i create a new minerva project, the same exception is thrown.

Maybe it's not related to the MacOS update, but i don't see what else could have changed. I will try on Windows.

**Comment by GlebBatykov** [comment]
Hi!

I didn't have the opportunity to test the framework on macOS (I don't have a Mac) and I suspected that Mac users might have some problems.

Everything works fine for me on Linux and Windows. I will try to investigate this problem.

**Comment by AreboursTLS** [comment]
I will continue on Windows.

Thx for your work and time.

**Comment by GlebBatykov** [comment]
If it's not difficult for you, write then you managed to run the server on Windows. And also, if possible, what you managed to implement using the framework.

I'm interested in getting some feedback.

**Comment by AreboursTLS** [comment]
No problem running on Windows and deploying on Google cloud run with the docker file. Quite easy ! It seems to be a Macos related issue. 

Il will try to investigate futher on mac.

**Comment by GlebBatykov** [comment]
Hi!

I tested the framework on macOS (13.1 Ventura) and found no problems when starting the server.
